services:
  - type: static
    name: endless-madness
    buildCommand: npm install && npm run build:prod
    staticPublishPath: ./dist/browser
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
      - src/**
      - package.json
      - angular.json
    headers:
      - path: /*
        name: X-Robots-Tag
        value: index
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
